### ISSUE TITLE
DataType definition file

### ISSUE THREAD

**Issue by jonathannaim** [jonathannaim/adaptablegrid#16]
Hey man,

Just had a look at the definition of the DataType interface that is being returned by Column.getType()
![image](https://cloud.githubusercontent.com/assets/12811036/26637761/428fafdc-4618-11e7-950f-9f30ee90edf8.png)

I'm sure something has gone wrong in the jsdoc to definition file of something...
Ideally, we'd want the method to be like that:
` getType(): 'String'|'Number'|'Boolean' ...........`

**Comment by jasonlipo** [comment]
How about changing the DataType to:
```typescript
enum DataType {
  String = 0,
  Number = 1,
  Boolean = 2,
  Date = 3,
  Object = 4
}
```

That's the only thing that would work with the existing source.
Now `getDataType(type: string): DataType` is effectively returning a number from 0 to 4, which means if it returns e.g. `DataType.String` then there's no error because they both compile down to numbers.

Maybe I'll try it and see if it doesn't throw an error with the Typescript compiler.

**Comment by jonathannaim** [comment]
Enum is definitely cleaner :) I wasn't sure you could generate it from the jsdoc. 

Nice one mate
